services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: prxnce14/my-web-app-backend:v0.1.9
    ports:
      - "${FLASK_RUN_PORT}:${FLASK_RUN_PORT}"
    volumes:
      - ./:/app
    env_file:
      - .env
    environment:
      - FLASK_ENV=development

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: prxnce14/my-web-app-frontend:v0.1.9
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - backend
    env_file:
      - .env
    