"""empty message

Revision ID: 15495cc875f7
Revises: dd398a8cc645
Create Date: 2025-05-07 01:56:03.327902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15495cc875f7'
down_revision = 'dd398a8cc645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(length=255), nullable=True))
        batch_op.drop_constraint('uq_restaurant_username', type_='unique')
        batch_op.create_unique_constraint('uq_restaurant_displayname', ['display_name'])
        batch_op.drop_column('username')
        batch_op.drop_column('lastname')
        batch_op.drop_column('firstname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstname', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lastname', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_constraint('uq_restaurant_displayname', type_='unique')
        batch_op.create_unique_constraint('uq_restaurant_username', ['username'])
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###
