"""Redid Driver model, view api

Revision ID: 4f837a678b6e
Revises: b2541a3a5740
Create Date: 2025-05-03 19:51:57.004767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f837a678b6e'
down_revision = 'b2541a3a5740'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('username', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('firstname', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('lastname', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('created_on', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uq_driver_username', ['username'])
        batch_op.drop_constraint('driver_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('address')
        batch_op.drop_column('agree_privacy')
        batch_op.drop_column('account_holder')
        batch_op.drop_column('user_id')
        batch_op.drop_column('emergency_contact_relationship')
        batch_op.drop_column('availablity_days')
        batch_op.drop_column('license_plate')
        batch_op.drop_column('emergency_contact_name')
        batch_op.drop_column('account_number')
        batch_op.drop_column('insurance_doc')
        batch_op.drop_column('dob')
        batch_op.drop_column('national_id')
        batch_op.drop_column('mobile_wallet')
        batch_op.drop_column('registration_doc')
        batch_op.drop_column('availablity_hours')
        batch_op.drop_column('vehicle_year')
        batch_op.drop_column('consent_background')
        batch_op.drop_column('agree_terms')
        batch_op.drop_column('emergency_contact_phone')
        batch_op.drop_column('profile_photo')
        batch_op.drop_column('consent_notifactions')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('vehicle_make_model')
        batch_op.drop_column('vehicle_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('vehicle_make_model', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bank_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('consent_notifactions', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('profile_photo', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_phone', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('agree_terms', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('consent_background', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('vehicle_year', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('availablity_hours', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('registration_doc', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mobile_wallet', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('national_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dob', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('insurance_doc', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('account_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('license_plate', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('availablity_days', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_relationship', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('account_holder', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('agree_privacy', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('driver_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.drop_constraint('uq_driver_username', type_='unique')
        batch_op.drop_column('created_on')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('email')
        batch_op.drop_column('lastname')
        batch_op.drop_column('firstname')
        batch_op.drop_column('password')
        batch_op.drop_column('username')
        batch_op.drop_column('user_type')

    # ### end Alembic commands ###
