"""empty message

Revision ID: 9a9278e7d944
Revises: 15495cc875f7
Create Date: 2025-05-10 20:28:00.316499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a9278e7d944'
down_revision = '15495cc875f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('liked_foods', sa.JSON(), nullable=True),
    sa.Column('dietary_restrictions', sa.JSON(), nullable=True),
    sa.Column('spice_level', sa.Integer(), nullable=False),
    sa.Column('healthy_level', sa.Integer(), nullable=False),
    sa.Column('sweet_preference', sa.Integer(), nullable=True),
    sa.Column('chicken', sa.Boolean(), nullable=True),
    sa.Column('fish', sa.Boolean(), nullable=True),
    sa.Column('pork', sa.Boolean(), nullable=True),
    sa.Column('goat', sa.Boolean(), nullable=True),
    sa.Column('beef', sa.Boolean(), nullable=True),
    sa.Column('no_meat', sa.Boolean(), nullable=True),
    sa.Column('other_meat', sa.String(length=100), nullable=True),
    sa.Column('cooking_jamaican', sa.Boolean(), nullable=True),
    sa.Column('cooking_indian', sa.Boolean(), nullable=True),
    sa.Column('cooking_chinese', sa.Boolean(), nullable=True),
    sa.Column('cooking_african', sa.Boolean(), nullable=True),
    sa.Column('cooking_vegan_ital', sa.Boolean(), nullable=True),
    sa.Column('cooking_italian', sa.Boolean(), nullable=True),
    sa.Column('other_cooking_style', sa.String(length=100), nullable=True),
    sa.Column('ackee_saltfish', sa.Boolean(), nullable=True),
    sa.Column('callaloo', sa.Boolean(), nullable=True),
    sa.Column('cooked_saltfish', sa.Boolean(), nullable=True),
    sa.Column('kidney', sa.Boolean(), nullable=True),
    sa.Column('liver', sa.Boolean(), nullable=True),
    sa.Column('fried_plantain', sa.Boolean(), nullable=True),
    sa.Column('dumplings', sa.Boolean(), nullable=True),
    sa.Column('festival', sa.Boolean(), nullable=True),
    sa.Column('breadfruit', sa.Boolean(), nullable=True),
    sa.Column('other_breakfast_items', sa.String(length=200), nullable=True),
    sa.Column('porridge', sa.Boolean(), nullable=True),
    sa.Column('scrambled_eggs', sa.Boolean(), nullable=True),
    sa.Column('pancakes', sa.Boolean(), nullable=True),
    sa.Column('french_toast', sa.Boolean(), nullable=True),
    sa.Column('waffles', sa.Boolean(), nullable=True),
    sa.Column('bacon', sa.Boolean(), nullable=True),
    sa.Column('sausage', sa.Boolean(), nullable=True),
    sa.Column('sandwich', sa.Boolean(), nullable=True),
    sa.Column('other_breakfast', sa.String(length=200), nullable=True),
    sa.Column('fry_chicken', sa.Boolean(), nullable=True),
    sa.Column('bake_chicken', sa.Boolean(), nullable=True),
    sa.Column('curry_goat', sa.Boolean(), nullable=True),
    sa.Column('soups', sa.Boolean(), nullable=True),
    sa.Column('steamed_fish', sa.Boolean(), nullable=True),
    sa.Column('escovitch_fish', sa.Boolean(), nullable=True),
    sa.Column('patty', sa.Boolean(), nullable=True),
    sa.Column('sandwiches', sa.Boolean(), nullable=True),
    sa.Column('pasta', sa.Boolean(), nullable=True),
    sa.Column('other_lunch', sa.String(length=200), nullable=True),
    sa.Column('pine_ginger', sa.Boolean(), nullable=True),
    sa.Column('callallo_juice', sa.Boolean(), nullable=True),
    sa.Column('june_plum', sa.Boolean(), nullable=True),
    sa.Column('guava_pine', sa.Boolean(), nullable=True),
    sa.Column('beet_root', sa.Boolean(), nullable=True),
    sa.Column('orange_juice', sa.Boolean(), nullable=True),
    sa.Column('other_juice', sa.String(length=200), nullable=True),
    sa.Column('budget', sa.String(length=10), nullable=False),
    sa.Column('order_times', sa.JSON(), nullable=True),
    sa.Column('additional_notes', sa.String(length=500), nullable=True),
    sa.Column('default_address', sa.String(length=255), nullable=False),
    sa.Column('delivery_instructions', sa.String(length=255), nullable=True),
    sa.Column('preferred_delivery_time', sa.String(length=20), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=True),
    sa.Column('sms_notifications', sa.Boolean(), nullable=True),
    sa.Column('promotional_emails', sa.Boolean(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.CheckConstraint("budget IN ('low', 'medium', 'high')", name='budget_choices'),
    sa.CheckConstraint("preferred_delivery_time IN ('morning', 'afternoon', 'evening')", name='delivery_time_choices'),
    sa.CheckConstraint('healthy_level >= 1 AND healthy_level <= 5', name='healthy_level_range'),
    sa.CheckConstraint('spice_level >= 1 AND spice_level <= 5', name='spice_level_range'),
    sa.CheckConstraint('sweet_preference >= 1 AND sweet_preference <= 5', name='sweet_preference_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_preferences')
    # ### end Alembic commands ###
