"""Fix Driver model column declarations

Revision ID: b2541a3a5740
Revises: e78988271ea9
Create Date: 2025-05-01 13:46:16.010301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2541a3a5740'
down_revision = 'e78988271ea9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver', schema=None) as batch_op:
        batch_op.add_column(sa.Column('insurance_doc', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('registration_doc', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('account_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('availablity_hours', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('availablity_days', sa.String(length=100), nullable=True))
        batch_op.drop_column('availablitity_hours')
        batch_op.drop_column('availablitity_days')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver', schema=None) as batch_op:
        batch_op.add_column(sa.Column('availablitity_days', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('availablitity_hours', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('availablity_days')
        batch_op.drop_column('availablity_hours')
        batch_op.drop_column('account_number')
        batch_op.drop_column('registration_doc')
        batch_op.drop_column('insurance_doc')

    # ### end Alembic commands ###
