"""empty message

Revision ID: d81115985165
Revises: e000615d56ca
Create Date: 2025-04-17 03:01:16.148750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd81115985165'
down_revision = 'e000615d56ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('username', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('firstname', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('lastname', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('created_on', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uq_users_username', ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_username', type_='unique')
        batch_op.drop_column('created_on')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('email')
        batch_op.drop_column('lastname')
        batch_op.drop_column('firstname')
        batch_op.drop_column('password')
        batch_op.drop_column('username')
        batch_op.drop_column('user_type')

    # ### end Alembic commands ###
