"""Add Driver model

Revision ID: e78988271ea9
Revises: d81115985165
Create Date: 2025-05-01 13:41:23.849525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e78988271ea9'
down_revision = 'd81115985165'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dob', sa.String(length=100), nullable=True),
    sa.Column('national_id', sa.String(length=100), nullable=True),
    sa.Column('profile_photo', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('vehicle_type', sa.String(length=100), nullable=True),
    sa.Column('vehicle_make_model', sa.String(length=255), nullable=True),
    sa.Column('vehicle_year', sa.String(length=100), nullable=True),
    sa.Column('license_plate', sa.String(length=100), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('account_holder', sa.String(length=100), nullable=True),
    sa.Column('mobile_wallet', sa.String(length=100), nullable=True),
    sa.Column('availablitity_hours', sa.String(length=100), nullable=True),
    sa.Column('availablitity_days', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_relationship', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=100), nullable=True),
    sa.Column('agree_terms', sa.Boolean(), nullable=True),
    sa.Column('agree_privacy', sa.Boolean(), nullable=True),
    sa.Column('consent_background', sa.Boolean(), nullable=True),
    sa.Column('consent_notifactions', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('driver')
    # ### end Alembic commands ###
